FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

# Install dependencies for OpenCV and Qt
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 libx11-dev libxkbcommon-x11-0 libqt5widgets5 && \
    apt-get clean

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "mnist_client.py"]
